# Generated by Django 4.2.6 on 2023-10-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intern',
        ),
    ]
