# Generated by Django 4.2.6 on 2023-11-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_intern_records_form_filled_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_records',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Weekly Hours'),
        ),
    ]
