# Generated by Django 4.2.6 on 2023-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_intern_records_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_records',
            name='academic_year',
            field=models.CharField(max_length=200, null=True, verbose_name='Academic Year'),
        ),
    ]
