# Generated by Django 4.2.6 on 2023-11-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_intern_records_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern_records',
            name='folder',
        ),
    ]
