# Generated by Django 4.2.6 on 2023-11-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_folder_record_delete_archivefolder'),
        ('signup', '0010_remove_intern_records_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern_records',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.folder'),
        ),
    ]
