# Generated by Django 4.2.6 on 2023-11-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_intern_records_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_records',
            name='course',
            field=models.CharField(choices=[('BSIT', 'BSIT'), ('BSIS', 'BSIS'), ('BSCS', 'BSCS'), ('BSA', 'BSA'), ('BSAIS', 'BSAIS'), ('BPA', 'BPA'), ('BSE', 'BSE')], max_length=10, null=True, verbose_name='Course'),
        ),
    ]
