# Generated by Django 4.2.6 on 2023-11-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_alter_intern_records_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_records',
            name='profile_image',
            field=models.ImageField(default='images/SSUlogo.png', upload_to='profile_images/'),
        ),
    ]
