# Generated by Django 4.2.6 on 2023-11-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybin',
            name='rendered_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
