# Generated by Django 4.2.6 on 2023-11-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_requirements_post_requirements_narrativereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
