# Generated by Django 4.2.6 on 2023-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_student_information_sheet_police_clearance_parent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay_clearance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='user',
        ),
        migrations.RemoveField(
            model_name='internship_agreement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medical_certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent_consent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent_id',
            name='user',
        ),
        migrations.RemoveField(
            model_name='police_clearance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student_information_sheet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Acceptance_Form',
        ),
        migrations.DeleteModel(
            name='Barangay_Clearance',
        ),
        migrations.DeleteModel(
            name='Cedula',
        ),
        migrations.DeleteModel(
            name='Internship_Agreement',
        ),
        migrations.DeleteModel(
            name='Medical_Certificate',
        ),
        migrations.DeleteModel(
            name='Parent_Consent',
        ),
        migrations.DeleteModel(
            name='Parent_ID',
        ),
        migrations.DeleteModel(
            name='Police_Clearance',
        ),
        migrations.DeleteModel(
            name='Student_Information_Sheet',
        ),
    ]
