# Generated by Django 4.2.6 on 2023-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_barangay_clearance_user_remove_cedula_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
