# Generated by Django 4.2.6 on 2023-10-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_intern_id_alter_intern_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=20, null=True),
        ),
    ]
