# Generated by Django 4.2.6 on 2023-10-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_intern_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intern',
        ),
    ]
